name: Build VSIX

on:
  pull_request:
    types: [opened, synchronize, labeled]

permissions:
  contents: write

jobs:
  build-vsix:
    if: "contains(github.event.pull_request.labels.*.name, 'autorelease: pending')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install latest npm (>= 11.5.1)
        run: |
          [ "$(printf '%s\n' "11.5.1" "$(npm -v)" | sort -V | head -n1)" = "11.5.1" ] || npm install -g npm@11.5.1
        shell: bash

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: |
          rm -f *.vsix
          npm run compile
          npm run vsce

      - name: Commit .vsix
        run: |
          git config user.email "95919151+yc-ui-bot@users.noreply.github.com"
          git config user.name "yc-ui-bot"
          git add -A -- '*.vsix'
          if git diff --cached --quiet; then
            echo "::info::.vsix is up to date"
          else
            git commit -m "chore: update vsix" --no-verify
            git push
          fi
